#!/bin/bash

ln -sf /bin/true shouldReboot
if [ "$USER" == "minecraft" ]
then
    cd /home/minecraft && screen -d -m -S minecraft ./rebootScript
else
    su - minecraft -c "cd /home/minecraft && screen -d -m -S minecraft ./rebootScript"
fi
